# Generated by Django 5.2.9 on 2025-12-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('relevance_to_kenya', models.TextField()),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ai_tech_stack', models.CharField(help_text='OpenAI, TensorFlow, LangChain', max_length=200)),
                ('impact_metric', models.CharField(help_text='e.g., Reduced manual work by 40%', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('live_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('business_type', models.CharField(max_length=100)),
                ('wants_ai_automation', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('status', models.CharField(default='new', max_length=20)),
            ],
        ),
    ]
